[package]
name = "aish"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
nix = { version = "0.29.0", features = ["process", "fs"] }
rustyline = { version = "14.0.0", features = ["with-file-history"] }
